# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
    - id: isort
      args:
        - --multi-line=3
        - --trailing-comma
        - --force-grid-wrap=0
        - --combine-as
        - --line-width=88
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.3.0
  hooks:
    - id: mypy
      exclude: ^(tests|sample_app)/
      args:
        - --ignore-missing-imports
        - --disallow-untyped-defs
        - --follow-imports
        - skip
- repo: https://github.com/PyCQA/autoflake
  rev: v2.2.0
  hooks:
    - id: autoflake
      args:
        - --in-place
        - --recursive
- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
    - id: black
