# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: local
  hooks:
    - id: trailing-whitespace-fixer
      name: trailing-whitespace-fixer
      language: system
      entry: trailing-whitespace-fixer
    - id: end-of-file-fixer
      name: end-of-file-fixer
      entry: end-of-file-fixer
      language: system
    - id: check-yaml
      name: check-yaml
      entry: check-yaml
      language: system
      types:
        - yaml
    - id: check-added-large-files
      name: check-added-large-files
      entry: check-added-large-files
      language: system
    - id: isort
      name: isort
      language: system
      entry: isort
    - id: mypy
      name: mypy
      language: system
      entry: mypy
      types:
        - python
      pass_filenames: false
    - id: black
      name: black
      language: system
      entry: black
      types:
        - python
    - id: autoflake
      name: autoflake
      language: system
      entry: autoflake
