language: python

cache: pip

python:
  - '3.6'
  - '3.7'
  - '3.8'

install:
  - sudo apt-get -y install upx-ucl curl
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
  - ~/.poetry/bin/poetry install

script:
  - scripts/test

after_script:
  - pip install codecov
  - codecov

.deploy_condition: &deploy_condition
  on:
    python: '3.7'
    tags: true
    repo: aogier/starlette-authlib

deploy:
  - provider: script
    script: ~/.poetry/bin/poetry build && ~/.poetry/bin/poetry publish
    <<: *deploy_condition
