---
name: Run Tests
on:
  - push
  - pull_request

jobs:

  run_tests:
    strategy:
      matrix:
        version:
          - 3.7
          - 3.8
          - 3.9
          - "3.10"
          - "3.11"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        env:
          DOCKER_BUILDKIT: 1
        run: |

          docker build . \
            --target test \
            --build-arg PYTHON_VERSION=${{ matrix.version }}
